export const differentiators = [
  "Transformo interface em percepcao de valor imediato.",
  "Projeto jornadas que combinam clareza, autoridade e conversao.",
  "Uno direcao visual, performance e execucao tecnica no mesmo padrao.",
] as const;

export const projects = [
  {
    slug: "exo-clinic",
    title: "Exo Clinic",
    category: "SaaS & Healthcare",
    description: "SaaS para clínicas e consultórios com agenda, pacientes, equipe, procedimentos e financeiro em uma operação unificada.",
    summary: "Uma operação clínica centralizada em uma interface mais confiável, limpa e preparada para reduzir fricção no dia a dia da equipe.",
    metrics: ["Real-time Data", "UX Focada", "Scalable"],
    tags: ["Next.js", "Node.js", "Arquitetura SaaS", "Dashboards"],
    accent: "from-[rgba(0,194,122,0.22)] via-[rgba(212,175,55,0.08)] to-transparent",
    challenge: "Clínicas sofriam com processos manuais fragmentados, risco de perda de dados e sistemas legados que deixavam a operação lenta.",
    solution: "Desenvolvi uma arquitetura moderna focada em UX rápida para médicos e recepcionistas, com leitura de dados em tempo real e fluxos protegidos.",
    stack: ["Next.js", "Node.js", "Tailwind", "PostgreSQL"],
    impact: [
      "Redução drástica no tempo de agendamento e onboarding",
      "Gestão de dados de pacientes unificada e segura",
      "Percepção de alto valor tecnológico pelos usuários da clínica",
    ],
    url: "https://exo-clinic.exocompany.com.br/login",
    status: "live",
  },
  {
    slug: "exo-barber",
    title: "Exo Barber Dashboard",
    category: "SaaS Barbearia & Gestão",
    description: "Dashboard de gestão para barbearias com foco em operação, leitura rápida de desempenho e acompanhamento centralizado do negócio.",
    summary: "Um painel operacional pensado para acompanhar fluxo de caixa, performance da equipe e indicadores do negócio com leitura direta.",
    metrics: ["Real-time Data", "UX Focada", "Scalable"],
    tags: ["React", "Supabase", "Analytics", "SaaS"],
    accent: "from-[rgba(212,175,55,0.18)] via-[rgba(0,194,122,0.08)] to-transparent",
    challenge: "A falta de visibilidade sobre as métricas diárias impedia donos de barbearias de tomarem decisões táticas baseadas em dados reais.",
    solution: "Criei painéis interativos de leitura rápida, destacando gargalos na operação, picos de atendimento e faturamento de forma instantânea.",
    stack: ["React", "TypeScript", "Supabase", "Tailwind"],
    impact: [
      "Leitura de margem de lucro acelerada",
      "Otimização no controle de agendas dos profissionais",
      "Interface fluida que reduz a curva de aprendizado",
    ],
    url: "https://exo-barber.vercel.app/dashboard",
    status: "live",
  },
  {
    slug: "aurea-link",
    title: "Aurea Link",
    category: "Enterprise Software",
    description: "Plataforma de prospecção B2B com automação comercial e posicionamento voltado para aumento de vendas com IA.",
    summary: "Uma ferramenta comercial desenhada para colocar a prospecção em piloto automático e escalar fechamentos com mais previsibilidade.",
    metrics: ["SSO Ready", "Compliance", "Uptime 99.9%"],
    tags: ["Autenticação", "React", "Gestão de Acessos", "Segurança"],
    accent: "from-[rgba(212,175,55,0.22)] via-[rgba(241,209,122,0.08)] to-transparent",
    challenge: "A empresa precisava de um hub centralizado que fosse blindado contra acessos indevidos, mas que não penalizasse a agilidade da equipe.",
    solution: "Implementei uma camada de autenticação rigorosa com uma interface de dashboard minimalista, focada inteiramente na tarefa do usuário.",
    stack: ["React", "Autenticação Moderna", "API Integration", "Motion"],
    impact: [
      "Nível enterprise de segurança na gestão de workflows",
      "Redução no tempo de resolução de tarefas operacionais",
      "Escalabilidade garantida para novos módulos internos",
    ],
    url: "https://aurea-link.exocompany.com.br/login",
    status: "live",
  },
  {
    slug: "bc-distributor",
    title: "BC Distributor",
    category: "E-commerce Premium (B2B)",
    description: "Plataforma wholesale para distribuição de beauty supply, orientada a catálogo, navegação comercial e conversão em contexto B2B.",
    summary: "Uma experiência de atacado digital criada para sustentar catálogo, navegação comercial e percepção de marca mais forte no segmento de beleza.",
    metrics: ["Fast LCP", "+ Conversão B2B", "SEO Otimizado"],
    tags: ["Next.js", "Integrações API", "Performance", "E-commerce"],
    accent: "from-[rgba(0,194,122,0.18)] via-[rgba(212,175,55,0.1)] to-transparent",
    challenge: "O catálogo antigo era pesado e não transmitia o posicionamento premium que os produtos de beleza exigiam para compras em grande volume.",
    solution: "Refiz o ecossistema focando em carregamento obsessivamente rápido e interfaces sofisticadas, otimizando o fluxo de pedido atacadista.",
    stack: ["Next.js", "TypeScript", "Tailwind", "Integrações de Pagamento"],
    impact: [
      "Aumento significativo na taxa de conversão",
      "Navegação fluida mesmo em dispositivos móveis 3G",
      "Estética visual alinhada ao alto padrão do nicho de beleza",
    ],
    url: "https://bcdistributor.vercel.app/",
    status: "live",
  },
  {
    slug: "achei-studios",
    title: "Achei Studios",
    category: "Agência Digital & Branding",
    description: "Marketplace do audiovisual para encontrar equipamentos, estúdios de fotografia, sets, podcasts e outros recursos de produção.",
    summary: "Uma plataforma de descoberta para o mercado audiovisual, conectando estrutura, espaço e recursos de produção em uma única experiência digital.",
    metrics: ["Motion Avançado", "Awwwards Level", "High FPS"],
    tags: ["Frontend Premium", "Motion", "UI/UX", "Branding"],
    accent: "from-[rgba(212,175,55,0.18)] via-[rgba(0,194,122,0.1)] to-transparent",
    challenge: "Agências criativas precisam de sites que sejam experiências inesquecíveis, o que muitas vezes destrói a performance da página.",
    solution: "Orquestrei animações complexas de scroll e hover usando framer-motion de forma otimizada, garantindo impacto cinematográfico sem engasgos.",
    stack: ["React", "Framer Motion", "Tailwind", "Frontend Architecture"],
    impact: [
      "Autoridade instantânea gerada no primeiro acesso",
      "Aumento do tempo médio de permanência na página",
      "Criação de um 'Sinal de Riqueza' visual para captação de clientes maiores",
    ],
    url: "https://acheistudios.com",
    status: "live",
  },
  {
    slug: "experts-marketing",
    title: "Experts Marketing",
    category: "Landing Page High-Ticket",
    description: "Landing page para comunidade de marketing digital, IA e crescimento, com proposta de entrada simples, troca real e direção prática.",
    summary: "Uma página construída para tornar o aprendizado no digital mais leve, confiável e organizado desde o primeiro contato.",
    metrics: ["Loading < 1s", "Conversão Otimizada", "Mobile First"],
    tags: ["Landing Page", "CRO", "Performance", "React"],
    accent: "from-[rgba(0,194,122,0.22)] via-[rgba(241,209,122,0.08)] to-transparent",
    challenge: "Cada segundo de loading em campanhas custa dinheiro. A página precisava ser agressiva visualmente, mas leve no processamento.",
    solution: "Código limpo, compressão de assets extrema e tipografia estrategicamente desenhada para guiar os olhos do usuário até o CTA.",
    stack: ["React", "Tailwind CSS", "Otimização Web", "Vercel"],
    impact: [
      "Custo por Aquisição (CPA) reduzido pela velocidade da página",
      "Leitura de proposta de valor clara e sem distrações",
      "Métricas de performance perfeitas no Google Lighthouse",
    ],
    url: "https://expertsmarketingdigital-landingpage.vercel.app/",
    status: "live",
  },
  {
    slug: "dr-jefferson-eves",
    title: "Dr. Jefferson Neves",
    category: "Autoridade Médica",
    description: "Presença digital para odontologia com foco em cuidado, estética, confiança e captação de pacientes em Joinville/SC.",
    summary: "Uma experiência que traduz cuidado clínico, exigência estética e confiança em uma jornada digital mais humana e convincente.",
    metrics: ["SEO Local", "Acessibilidade", "Confiança Visual"],
    tags: ["Next.js", "UI/UX", "Saúde", "SEO"],
    accent: "from-[rgba(212,175,55,0.16)] via-[rgba(0,194,122,0.08)] to-transparent",
    challenge: "Transmitir excelência médica no ambiente digital, superando templates genéricos que não geram autoridade.",
    solution: "Desenvolvimento de uma interface sóbria, elegante e focada em prova social e facilidade de agendamento de consultas.",
    stack: ["Next.js", "TypeScript", "Tailwind CSS"],
    impact: [
      "Construção de posicionamento digital premium em desenvolvimento",
      "Estrutura otimizada para buscas de especialidades médicas",
    ],
    url: "https://drjeffersoneves.vercel.app/",
    status: "development",
  },
  {
    slug: "synfau",
    title: "Synfau Website",
    category: "Web Application",
    description: "Aplicação web em construção com posicionamento de produto próprio e base pensada para crescimento, modularidade e novas integrações.",
    summary: "Uma fundação de produto desenhada para crescer com consistência, mantendo espaço para evolução funcional e expansão técnica.",
    metrics: ["Arquitetura Clean", "Em Dev", "Escalabilidade"],
    tags: ["Next.js", "Full Stack", "Inovação", "Arquitetura"],
    accent: "from-[rgba(0,194,122,0.16)] via-[rgba(212,175,55,0.08)] to-transparent",
    challenge: "Projetar a base de um sistema robusto que precisa ser rápido agora e flexível para os requisitos do futuro.",
    solution: "Aplicação de padrões de engenharia de software rigorosos, preparando o terreno com Next.js para renderização híbrida.",
    stack: ["Next.js", "TypeScript", "Frontend Engineering", "Vercel"],
    impact: [
      "Redução de débito técnico antes mesmo do lançamento",
      "Ambiente preparado para iterações ágeis (CI/CD)",
    ],
    url: "https://synfau.vercel.app/",
    status: "development",
  },
] as const;

export const technologies = [
  {
    name: "Next.js",
    category: "Core",
    level: 95,
    detail: "Arquitetura moderna, App Router e performance real.",
  },
  {
    name: "React",
    category: "Core",
    level: 94,
    detail: "Interfaces complexas com alto controle de estado e fluidez.",
  },
  {
    name: "TypeScript",
    category: "Production",
    level: 92,
    detail: "Base segura para produtos serios e evolutivos.",
  },
  {
    name: "Tailwind",
    category: "Advanced",
    level: 90,
    detail: "Velocidade visual sem perder acabamento de alto padrao.",
  },
  {
    name: "Motion",
    category: "Interaction",
    level: 88,
    detail: "Microinteracoes, storytelling e ritmo cinematografico.",
  },
  {
    name: "Node.js",
    category: "Production",
    level: 86,
    detail: "Backends e integracoes preparados para escala.",
  },
  {
    name: "Automation",
    category: "Automation",
    level: 84,
    detail: "Fluxos inteligentes com foco em ganho operacional.",
  },
  {
    name: "Figma",
    category: "Interface",
    level: 89,
    detail: "Sistemas visuais e prototipacao de alta fidelidade.",
  },
] as const;


